language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -y gfortran

# command to install dependencies
install:
  - pip install numpy
  - python setup.py install

# command to run tests
# script: nosetests
script:
  - python unittests.py

